// Données lieux — partie 1
LOCS.push(...[
  { id:1, name:"Tintagel", lat:50.666, lng:-4.749, cat:"arthur",
    region:"Cornouailles, Angleterre",
    desc:"Lieu de la conception et naissance du roi Arthur. Uther Pendragon, transformé par Merlin à l'image du duc Gorlois, s'unit à Ygerne/Igraine et engendre Arthur. Le château est aussi la cour du Roi Marc dans les légendes tristaniennes.",
    chars:["Arthur","Uther Pendragon","Ygerne / Igraine","Merlin","Gorlois (duc de Cornouailles)"],
    events:["Conception magique d'Arthur (Uther / Ygerne)","Naissance d'Arthur","Remise d'Arthur à Merlin","Cour du Roi Marc (légende tristanienne)"],
    sources:["Geoffrey de Monmouth, Historia Regum Britanniae (c.1138), Livre VIII","Wace, Roman de Brut (1155)","Layamon, Brut (c.1190)","Malory, Le Morte d'Arthur (1485), Livre I"] },

  { id:2, name:"Camelot — Winchester", lat:51.063, lng:-1.308, cat:"arthur",
    region:"Hampshire, Angleterre",
    desc:"Camelot tel qu'identifié par Thomas Malory. Winchester abrite la Winchester Round Table (XIIIe s.), table ronde médiévale peinte, suspendue dans la Great Hall. Siège permanent de la Table Ronde, cœur politique et chevaleresque du royaume d'Arthur.",
    chars:["Arthur","Guinevere","Lancelot","Gawain","Perceval","Galahad","Bohort","Kay","Bedivere — tous les chevaliers"],
    events:["Siège de la Table Ronde","Tournois royaux","Départ solennel de la Quête du Graal","Retour des chevaliers",  "Accusation de Guinevere","Procès et bûcher de Guinevere"],
    sources:["Malory, Le Morte d'Arthur (1485)","Wace, Roman de Brut (1155 — 1ère mention de la Table Ronde)","Chrétien de Troyes (Yvain, Lancelot, Perceval — Camelot mentionné)","Cycle Vulgate (Lancelot-Graal)"] },

  { id:3, name:"Cadbury Castle (Camelot candidat)", lat:51.022, lng:-2.528, cat:"arthur",
    region:"Somerset, Angleterre",
    desc:"Principale candidate archéologique pour Camelot. Forteresse de l'âge du fer réoccupée aux Ve–VIe siècles. John Leland (1542) est le premier à l'identifier avec Camelot. Les fouilles de Leslie Alcock (1966–1970) ont révélé une grande salle sub-romaine et une enceinte renforcée.",
    chars:["Arthur (historique hypothétique — chef de guerre breton, Ve–VIe s.)"],
    events:["Occupation sub-romaine fortifiée (Ve–VIe s.)","Identification comme Camelot par John Leland (1542)","Fouilles archéologiques (Alcock, 1966–1970)"],
    sources:["John Leland, Itinerary (1542)","Leslie Alcock, Arthur's Britain (1971)","Geoffrey Ashe, The Discovery of King Arthur","Fouilles archéologiques modernes"] },

  { id:4, name:"Caerleon-sur-Usk", lat:51.607, lng:-2.949, cat:"arthur",
    region:"Monmouthshire, Galles du Sud",
    desc:"La 'Cité des Légions' (Isca Silurum). Principale cour royale d'Arthur selon Geoffrey de Monmouth — la plus solennelle. Arthur y tient sa grande plénière de cour avec tous les rois vassaux de Bretagne, reçoit l'hommage de Rome, et nomme ses chevaliers.",
    chars:["Arthur","Guinevere","Gawain","Kay","Bedivere","Lancelot (dans Chrétien)","Perceval (dans Chrétien)"],
    events:["Grande plénière de cour arthurienne","Couronnement solennel d'Arthur","Refus de l'ambassade romaine","Réception des rois vassaux"],
    sources:["Geoffrey de Monmouth, Historia Regum Britanniae (Livre IX)","Chrétien de Troyes, Erec et Enide (c.1170)","Chrétien de Troyes, Perceval (c.1182)","Giraldus Cambrensis, Itinerarium Kambriae"] },

  { id:5, name:"Glastonbury / Avalon", lat:51.145, lng:-2.716, cat:"arthur",
    region:"Somerset, Angleterre",
    desc:"Identifié comme l'île d'Avalon où Arthur est emmené pour guérir après Camlann. En 1191, les moines de Glastonbury prétendent découvrir la tombe avec l'inscription : 'Hic jacet sepultus inclitus rex Arthurus in insula Avalonia'. L'abbaye est aussi liée au Graal via Joseph d'Arimathie.",
    chars:["Arthur","Guinevere","Morgan le Fay","Morgause","Dame du Lac","Joseph d'Arimathie"],
    events:["Translation d'Arthur mourant vers Avalon","Découverte prétendue de la tombe (1191)","Fondation du christianisme en Bretagne insulaire par Joseph d'Arimathie","Inhumation de Guinevere"],
    sources:["Geoffrey de Monmouth, Vita Merlini (c.1150)","Giraldus Cambrensis, De Instructione Principis","Cycle Vulgate (La Queste del Saint Graal)","Malory, Le Morte d'Arthur"] },

  { id:6, name:"Londres (Londinium)", lat:51.507, lng:-0.127, cat:"arthur",
    region:"Angleterre",
    desc:"Selon Geoffrey de Monmouth, Arthur est couronné à Londres, capitale de Logres. Dans plusieurs traditions, c'est ici que se trouve l'Épée dans la Pierre ou dans l'Enclume, que seul Arthur peut tirer. La Tour de Londres est mentionnée dans les romances médiévales arthuriennes.",
    chars:["Arthur","Uther Pendragon","Merlin","Archeveque de Canterbury"],
    events:["Couronnement d'Arthur roi de Bretagne","L'Épée dans la Pierre / l'Enclume","Rassemblement des rois récalcitrants","Administration du royaume de Logres"],
    sources:["Geoffrey de Monmouth, Historia Regum Britanniae","Malory, Le Morte d'Arthur (Livre I)","Wace, Roman de Brut"] },

  { id:7, name:"Mons Badonicus — Bath", lat:51.375, lng:-2.359, cat:"arthur",
    region:"Bath / Somerset, Angleterre",
    desc:"Principale candidate pour la bataille de Badon, victoire décisive des Bretons contre les Saxons. Gildas (De Excidio, c.540) la cite sans nommer Arthur. Nennius (c.830) en attribue la victoire à Arthur, qui aurait porté seul l'image de la Vierge. Arrêt d'une génération de l'avancée saxonne.",
    chars:["Arthur (dux bellorum selon Nennius)","Saxons vaincus"],
    events:["Bataille de Mons Badonicus (c.490–516)","12e et ultime victoire d'Arthur selon Nennius","Arrêt de l'expansion saxonne pour une génération"],
    sources:["Gildas, De Excidio et Conquestu Britanniae (c.540)","Bède, Historia Ecclesiastica (731)","Nennius, Historia Brittonum (c.830)","Geoffrey de Monmouth (Kaerbadus)","Annales Cambriae"] },

  { id:8, name:"Camlann — Rivière Camel", lat:50.630, lng:-4.830, cat:"arthur",
    region:"Cornouailles, Angleterre",
    desc:"Candidate principale pour Camlann, last battle (Annales Cambriae c.950 : 'bellum Camlan' en 537). La rivière Camel (Camblan en cornique, 'coude de rivière') près de Camelford est convaincante étymologiquement. C'est ici qu'Arthur et Mordred s'affrontent pour la dernière fois.",
    chars:["Arthur","Mordred","Bedivere (jette Excalibur)","Lucan le Bouteiller"],
    events:["Bataille de Camlann / Camblan (c.537)","Mort de Mordred (tué par Arthur)","Blessure mortelle d'Arthur","Remise d'Excalibur au lac par Bedivere","Départ d'Arthur vers Avalon"],
    sources:["Annales Cambriae (c.950)","Geoffrey de Monmouth (Historia Regum Britanniae)","Triades galloises","Malory, Le Morte d'Arthur (Livre XXI)","Cycle Vulgate (La Mort le Roi Artu)"] },

  { id:9, name:"Camboglanna / Birdoswald", lat:54.987, lng:-2.602, cat:"arthur",
    region:"Cumbria, Mur d'Hadrien, Angleterre",
    desc:"Fort romain Camboglanna sur le Mur d'Hadrien, proposé par Kenneth Jackson et John Morris comme site de la bataille de Camlann. Camboglanna = 'crooked bank / coude de rivière' en brittonique. Le site montre une réoccupation sub-romaine significative au Ve–VIe s.",
    chars:["Arthur (hypothétique)","Mordred"],
    events:["Camlann (candidat alternatif) — Mur d'Hadrien","Réoccupation sub-romaine du fort"],
    sources:["Kenneth Jackson (linguistic analysis)","John Morris, The Age of Arthur (1973)","Fouilles de Birdoswald (1988–1999)"] },

  { id:10, name:"Plaine de Salisbury", lat:51.178, lng:-1.826, cat:"arthur",
    region:"Wiltshire, Angleterre",
    desc:"Dans le Cycle Vulgate et chez Malory, la bataille finale Arthur/Mordred se tient sur la plaine de Salisbury, à proximité de Stonehenge. Arthur transperce Mordred de sa lance et reçoit un coup mortel à la tête.",
    chars:["Arthur","Mordred","Bedivere","Lucan le Bouteiller","Chevaliers des deux camps"],
    events:["Bataille de la Plaine de Salisbury (=Camlann selon Malory)","Mort de Mordred","Dernière blessure d'Arthur","Remise d'Excalibur au lac"],
    sources:["Cycle Vulgate, La Mort le Roi Artu","Malory, Le Morte d'Arthur (Livre XXI)"] },

  { id:11, name:"York (Eboracum)", lat:53.960, lng:-1.087, cat:"arthur",
    region:"Yorkshire, Angleterre",
    desc:"York, capitale romaine du nord (Eboracum). Geoffrey de Monmouth y situe des conseils royaux post-victorieux d'Arthur contre les Saxons. Siège de l'archevêché du nord, lieu de réconciliation et d'administration.",
    chars:["Arthur","Lot de Lothian","Lancelot (campagne du nord)"],
    events:["Conseil royal après victoires saxonnes","Administration des royaumes du Nord","Campagnes arthuro-bretonnes"],
    sources:["Geoffrey de Monmouth, Historia Regum Britanniae"] },

  { id:12, name:"Carlisle (Luguvallium)", lat:54.895, lng:-2.938, cat:"arthur",
    region:"Cumbria, Angleterre",
    desc:"Siège fréquent de la cour d'Arthur dans les romances anglaises du nord. Lieu de Pentecôte pour Arthur dans les ballades médiévales. Le Chevalier Vert fait son entrée à la cour d'Arthur ici (non nommé mais identifié par les modernes).",
    chars:["Arthur","Guinevere","Gawain","Kay (sénéchal)","Chevalier Vert (association)"],
    events:["Cour de Pentecôte d'Arthur","Aventures du nord","Tournois et joutes"],
    sources:["Awntryrs off Arthure (c.1400)","Wedding of Sir Gawain and Dame Ragnell","Romances anglaises médiévales (XIVe–XVe s.)"] },

]);
